### ISSUE TITLE
Publish to Clojars!

### ISSUE THREAD

**Issue by sundbry** [onyx-platform/onyx-amazon-kinesis#11]
Hi Luke,

The last release(s) haven't published to Clojars since 0.12.0.0 - would you mind republishing when you get a chance please?

**Comment by lbradstreet** [comment]
Ah right. I disabled the CI builds and autodeploy, because it was running
up kinesis fees when a build would die and it wouldn't clean up the stream.
I've deployed 0.14.1.1 for you manually.

**Comment by sundbry** [comment]
Thanks a lot. I'll have to buy you a drink when I come to Seattle again!
