### ISSUE TITLE
Require missing for onyx.tasks.kinesis

### ISSUE THREAD

**Issue by j0ni** [onyx-platform/onyx-amazon-kinesis#7]
Line 121 of `onyx.plugins.kinesis` references the `onyx.tasks.kinesis` namespace, but it has not been required.

Workaround is to require `onyx.tasks.kinesis` in the boot namespace before `onyx.plugins.kinesis`. Adding the require at the top of `onyx.plugins.kinesis` would fix this.

**Comment by lbradstreet** [comment]
Thank you. Fixed.
